import { PrismaClient } from '@prisma/client'
import bcrypt from 'bcryptjs'

const prisma = new PrismaClient()
const channels = ['INTERCOM', 'EMAIL', 'APP_STORE', 'SIMULATED']
const samples = [
  ['The new onboarding checklist made setup much easier.', 'Onboarding'], ['I keep getting logged out while switching projects.', 'Reliability'], ['Please add dark mode to the dashboard.', 'Customization'], ['Exporting a report takes too many clicks.', 'Reporting'], ['The mobile experience feels cramped on smaller screens.', 'Mobile experience'], ['Search does not find older conversations.', 'Search'], ['Our team needs better permissions for external guests.', 'Workspace management'], ['The integrations page is confusing to configure.', 'Integrations'], ['I love the weekly digest; it keeps our team aligned.', 'Reporting'], ['Notifications arrive several hours late.', 'Reliability']
]
async function main() { const workspace = await prisma.workspace.upsert({ where: { id: 'demo-workspace' }, update: {}, create: { id: 'demo-workspace', name: 'Acme, Inc.' } }); const users = [{ name: 'Avery Chen', email: 'admin@loop.demo', role: 'ADMIN' }, { name: 'Maya Patel', email: 'analyst@loop.demo', role: 'ANALYST' }, { name: 'Noah Williams', email: 'viewer@loop.demo', role: 'VIEWER' }]; for (const u of users) await prisma.user.upsert({ where: { email: u.email }, update: { role: u.role }, create: { ...u, passwordHash: await bcrypt.hash('loop-demo-2025', 12), workspaceId: workspace.id } }); for (const [, name] of samples) await prisma.theme.upsert({ where: { workspaceId_name: { workspaceId: workspace.id, name } }, update: {}, create: { name, workspaceId: workspace.id, description: `Feedback related to ${name.toLowerCase()}.` } }); const themes = await prisma.theme.findMany({ where: { workspaceId: workspace.id } }); for (let i = 0; i < 128; i++) { const [content, themeName] = samples[i % samples.length]; const sentiment = i % 5 === 0 ? 'NEG' : i % 3 === 0 ? 'POS' : 'NEU'; const feedback = await prisma.feedback.create({ data: { content, channel: channels[i % channels.length], customerLabel: `Customer ${String(i + 1).padStart(3, '0')}`, sentiment, sentimentScore: sentiment === 'NEG' ? -0.6 : sentiment === 'POS' ? 0.75 : 0, featureArea: themeName, workspaceId: workspace.id, status: i % 4 === 0 ? 'REVIEWED' : 'NEW' } }); const theme = themes.find((t) => t.name === themeName); if (theme) await prisma.feedbackTheme.create({ data: { feedbackId: feedback.id, themeId: theme.id, confidence: 0.92 } }) } console.log('LOOP demo data seeded. Password for demo users: loop-demo-2025') }
main().finally(() => prisma.$disconnect())
